# Generated by Django 4.1.2 on 2022-12-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_myuser_default_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='default_pic',
        ),
    ]
