# Generated by Django 4.1.2 on 2023-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_myuser_default_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
