# Generated by Django 4.1.2 on 2023-01-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_myuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DurationField(auto_created=True)),
                ('story', models.ImageField(upload_to='stories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
